name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov pymongo fastapi httpx motor

      # Verifica si hay archivos C y configura en consecuencia
      - name: Detect C files and setup
        id: detect-c
        run: |
          if [ -n "$(find . -name '*.c' -o -name '*.h')" ]; then
            echo "C_FILES_EXIST=true" >> $GITHUB_OUTPUT
            sudo apt-get update
            sudo apt-get install -y build-essential bear
          else
            echo "C_FILES_EXIST=false" >> $GITHUB_OUTPUT
          fi

      # Solo generar compile_commands.json si hay archivos C
      - name: Generate compilation database
        if: steps.detect-c.outputs.C_FILES_EXIST == 'true'
        run: |
          # Lista los archivos C encontrados
          find . -name "*.c" -o -name "*.h"
          # Intenta compilar con gcc como fallback si make falla
          bear -- gcc -c $(find . -name "*.c") || echo "Warning: Could not generate complete compile_commands.json"

      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --cov=Services --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ISCODEVUTB_CodeForGood
            -Dsonar.organization=deviscoutb
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.shell.file.suffixes=-
            -Dsonar.ps.file.suffixes=-
            ${{ steps.detect-c.outputs.C_FILES_EXIST == 'true' && '-Dsonar.cfamily.compile-commands=compile_commands.json -Dsonar.c.file.suffixes=.c,.h' || '-Dsonar.c.file.suffixes=- -Dsonar.cpp.file.suffixes=- -Dsonar.objc.file.suffixes=-' }}
