- name: Run tests with coverage
  run: |
    pytest --cov=./ \
           --cov-config=.coveragerc \
           --cov-report=xml \
           --cov-report=term-missing:skip-covered \
           --junitxml=test-results.xml
    python -m coverage report --show-missing

- name: SonarQube Scan
  uses: SonarSource/sonarqube-scan-action@v4
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  with:
    args: >
      -Dsonar.projectKey=ISCODEVUTB_CodeForGood
      -Dsonar.organization=deviscoutb
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.python.coverage.reportPaths=coverage.xml
      -Dsonar.testExecutionReportPaths=test-results.xml
      -Dsonar.coverage.exclusions=**/__init__.py,**/tests/**,**/migrations/**
      -Dsonar.qualitygate.wait=true
      -Dsonar.qualitygate.timeout=600
